spring:
    profiles:
        active: '@spring.profiles.active@'
   
server:
    port: 5000 
    error:
        whitelabel:
            enabled: false  
     
app: 
    datasource:
        jdbc-url: jdbc:postgresql://aa1eutbh9gpqsvr.cfrwarbl7jf8.us-east-1.rds.amazonaws.com:5432/ebdb
        username: aaminopro
        password: HEXB16OCTALB8
        pool-size: 50   
 
